### ISSUE TITLE
About command "git commit -am" in README.md

### ISSUE THREAD

**Issue by diligejy** [dl4ab/dl4ab.github.io#25]
> commit 명령에 -am 옵션을 사용하면 스테이지에 올리고 커밋하는 과정을 한꺼번에 처리할 수 있습니다. 단, 이 방법은 한 번이라도 커밋한 적이 있는 파일을 다시 커밋할 때만 사용할 수 있습니다.
> 출처 : 지옥에서 온 문서관리자 깃&깃허브 입문 51p

위 책에 따르면 한 번 이상 커밋을 해야 commit -am을 사용할 수 있다고 나와있습니다.
그런데 블로그 작성자는 글을 작성한 뒤에 commit을 처음하는 경우가 많을 거고, 그렇다면 add와 commit을 나눠서 실행해야합니다.
 
따라서 README.md에 나와있는 git commit -am이란 명령어를 고쳐야 할거 같다는 생각이 들었는데 어떻게 생각하시나요?

**Comment by kkweon** [comment]
좋은 이슈입니다 교육생.

분명히 이슈는 맞는데 설명이 잘못되었습니다.

```diff
- 그런데 블로그 작성자는 글을 작성한 뒤에 commit을 처음하는 경우가 많을 거고, 그렇다면 add와 commit을 나눠서 실행해야합니다.
+ 그런데 블로그 글이 처음 생성될 때 commit 이 한번도 되지 않은 상태이기 때문에 `add` 와 `commit` 을 나눠서 실행해야 합니다.
```

**Comment by diligejy** [comment]
악 정확히 말하겠습니다
